version: 1



formatters:
  tuna_standard:
    format: "%(asctime)s | %(name)s:%(levelname)s | %(module)s:%(funcName)s | %(message)s"
  tuna_simple:
    format: '%(levelname)s | %(module)s:%(funcName)s | %(message)s'



handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: tuna_simple
    stream: ext://sys.stdout
  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: tuna_standard
    filename: log/info.log
    maxBytes: 100000
    backupCount: 3
    encoding: utf8
  root_info_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: tuna_standard
    filename: log/root_info.log
    maxBytes: 100000
    backupCount: 3
    encoding: utf8



loggers:
  debugLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  fetchersLogger:
    level: DEBUG
    handlers: [info_handler, console]
    propagate: no
root:
  level: DEBUG
  handlers: [root_info_handler]
