version: 1



formatters:
  standard:
    format: "%(asctime)s | %(name)s:%(levelname)s | %(module)s:%(funcName)s | %(message)s"
  simple:
    format: '%(asctime)s | %(name)s:%(levelname)s | %(module)s:%(funcName)s | %(message)s'



handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: log/info.log
    maxBytes: 100000
    backupCount: 3
    encoding: utf8



loggers:
  debugLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  fetchersLogger:
    lefet: DEBUG
    handlers: [info_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
